version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule: { interval: "weekly" }
    open-pull-requests-limit: 5
    labels: ["deps","frontend","ci"]
    groups:
      minor-and-patch:
        update-types: ["minor","patch"]
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule: { interval: "monthly" }
    labels: ["deps","ci"]
