// src/components/lists/automacoesPadrao.ts
import type { AutomacaoNotificacao } from "@/types/automacao";

export const automacoesPadrao: AutomacaoNotificacao[] = [
  {
    id: "1",
    nome: "Confirmação de pagamento",
    descricao: "Mensagem automática ao aprovar um pagamento.",
    gatilho: "Pagamento aprovado",
    canal: ["E-mail", "Push"],
    obrigatoria: true,
    status: "ativo",
  },
  {
    id: "2",
    nome: "Lembrete de vencimento (7 dias)",
    descricao: "Lembrete enviado 7 dias antes do vencimento da fatura.",
    gatilho: "7 dias antes do vencimento",
    canal: ["E-mail", "WhatsApp"],
    obrigatoria: true,
    status: "ativo",
  },
  {
    id: "3",
    nome: "Lembrete de vencimento (1 dia)",
    descricao: "Lembrete enviado 1 dia antes do vencimento da fatura.",
    gatilho: "1 dia antes do vencimento",
    canal: ["E-mail", "WhatsApp"],
    obrigatoria: true,
    status: "ativo",
  },
  {
    id: "4",
    nome: "Aviso de inadimplência",
    descricao: "Aviso automático quando a fatura está em atraso.",
    gatilho: "Fatura vencida",
    canal: ["E-mail", "WhatsApp"],
    obrigatoria: true,
    status: "ativo",
  },
  {
    id: "5",
    nome: "Confirmação de ativação do trial",
    descricao: "Confirmação automática ao ativar período de teste.",
    gatilho: "Ativação do trial",
    canal: ["E-mail", "Push"],
    obrigatoria: true,
    status: "ativo",
  },
  {
    id: "6",
    nome: "Aviso de término do trial (3 dias)",
    descricao: "Alerta de que o período de teste está acabando em 3 dias.",
    gatilho: "3 dias antes do fim do trial",
    canal: ["E-mail", "Push"],
    obrigatoria: true,
    status: "ativo",
  },
  {
    id: "7",
    nome: "Aviso de término do trial (1 dia)",
    descricao: "Alerta de que o período de teste está acabando em 1 dia.",
    gatilho: "1 dia antes do fim do trial",
    canal: ["E-mail", "Push"],
    obrigatoria: true,
    status: "ativo",
  },
  {
    id: "8",
    nome: "Oferta após término do trial",
    descricao: "Oferta automática para converter usuário de teste em cliente.",
    gatilho: "Após término do trial",
    canal: ["E-mail", "Push"],
    obrigatoria: true,
    status: "ativo",
  },
  {
    id: "9",
    nome: "Boas-vindas ao presidente",
    descricao: "Mensagem automática de boas-vindas ao criar conta de racha.",
    gatilho: "Conta criada",
    canal: ["E-mail", "Push"],
    obrigatoria: true,
    status: "ativo",
  },
  {
    id: "10",
    nome: "Alerta de alteração de dados sensíveis",
    descricao: "Aviso automático ao alterar dados críticos (e-mail, senha).",
    gatilho: "Alteração de dados sensíveis",
    canal: ["E-mail"],
    obrigatoria: true,
    status: "ativo",
  },
  {
    id: "11",
    nome: "Alerta de login suspeito",
    descricao: "Aviso automático em caso de login em dispositivo não reconhecido.",
    gatilho: "Login suspeito",
    canal: ["E-mail"],
    obrigatoria: true,
    status: "ativo",
  },
  {
    id: "12",
    nome: "Notificação de atualização importante",
    descricao: "Comunicado de atualizações críticas e manutenções.",
    gatilho: "Atualização do sistema",
    canal: ["E-mail", "Push"],
    obrigatoria: true,
    status: "ativo",
  },
  {
    id: "13",
    nome: "Novas funcionalidades essenciais",
    descricao: "Aviso automático sobre funções essenciais liberadas.",
    gatilho: "Nova funcionalidade",
    canal: ["E-mail", "Push"],
    obrigatoria: true,
    status: "ativo",
  },
  {
    id: "14",
    nome: "Comunicados oficiais",
    descricao: "Comunicados institucionais importantes do Fut7Pro.",
    gatilho: "Comunicado institucional",
    canal: ["E-mail", "Push"],
    obrigatoria: true,
    status: "ativo",
  },
];
