import type { LancamentoFinanceiro } from "@/types/financeiro";

export const mockLancamentosFinanceiro: LancamentoFinanceiro[] = [
  {
    id: "1",
    data: "2025-06-25",
    tipo: "entrada",
    categoria: "diaria",
    descricao: "Diarias dos jogadores - 11 pagantes",
    valor: 132,
    responsavel: "AdminX",
  },
  {
    id: "2",
    data: "2025-06-25",
    tipo: "entrada",
    categoria: "patrocinio",
    descricao: "Patrocinio Supermercado ABC",
    valor: 200,
    responsavel: "AdminY",
  },
  {
    id: "3",
    data: "2025-06-25",
    tipo: "saida",
    categoria: "despesa",
    descricao: "Pagamento arbitragem",
    valor: 60,
    responsavel: "AdminX",
  },
  {
    id: "4",
    data: "2025-06-24",
    tipo: "entrada",
    categoria: "mensalidade",
    descricao: "Mensalidade antecipada - Joao Mensalista",
    valor: 40,
    responsavel: "AdminY",
  },
  {
    id: "5",
    data: "2025-06-24",
    tipo: "saida",
    categoria: "despesa",
    descricao: "Compra bolas oficiais",
    valor: 100,
    responsavel: "AdminX",
  },
  {
    id: "6",
    data: "2025-06-23",
    tipo: "entrada",
    categoria: "evento",
    descricao: "Rifa camisa oficial",
    valor: 120,
    responsavel: "AdminY",
  },
  {
    id: "7",
    data: "2025-06-23",
    tipo: "saida",
    categoria: "despesa",
    descricao: "Lavagem de uniformes",
    valor: 30,
    responsavel: "AdminY",
  },
  {
    id: "8",
    data: "2025-06-22",
    tipo: "saida",
    categoria: "despesa_adm",
    descricao: "Despesas de coordenacao",
    valor: 80,
    responsavel: "AdminX",
  },
  {
    id: "9",
    data: "2025-06-22",
    tipo: "saida",
    categoria: "sistema",
    descricao: "Pagamento do nosso site",
    valor: 200,
    responsavel: "AdminY",
  },
];
