import type { LancamentoFinanceiro } from "@/types/financeiro";

export const mockLancamentosFinanceiro: LancamentoFinanceiro[] = [
  {
    id: "1",
    data: "2025-06-25",
    tipo: "diaria",
    descricao: "Diárias dos jogadores - 11 pagantes",
    valor: 132,
    responsavel: "AdminX",
  },
  {
    id: "2",
    data: "2025-06-25",
    tipo: "patrocinio",
    descricao: "Patrocínio Supermercado ABC",
    valor: 200,
    responsavel: "AdminY",
  },
  {
    id: "3",
    data: "2025-06-25",
    tipo: "despesa",
    descricao: "Pagamento arbitragem",
    valor: -60,
    responsavel: "AdminX",
  },
  {
    id: "4",
    data: "2025-06-24",
    tipo: "mensalidade",
    descricao: "Mensalidade antecipada - João Mensalista",
    valor: 40,
    responsavel: "AdminY",
  },
  {
    id: "5",
    data: "2025-06-24",
    tipo: "despesa",
    descricao: "Compra bolas oficiais",
    valor: -100,
    responsavel: "AdminX",
  },
  {
    id: "6",
    data: "2025-06-23",
    tipo: "evento",
    descricao: "Rifa camisa oficial",
    valor: 120,
    responsavel: "AdminY",
  },
  {
    id: "7",
    data: "2025-06-23",
    tipo: "despesa",
    descricao: "Lavagem de uniformes",
    valor: -30,
    responsavel: "AdminY",
  },
  {
    id: "8",
    data: "2025-06-22",
    tipo: "despesa_adm",
    descricao: "Despesas de Coordenação",
    valor: -80,
    responsavel: "AdminX",
  },
  {
    id: "9",
    data: "2025-06-22",
    tipo: "sistema",
    descricao: "Pagamento do nosso site",
    valor: -200,
    responsavel: "AdminY",
  },
];
