import type { Notificacao } from "@/types/notificacao";

export const mockNotificacoes: Notificacao[] = [
  {
    id: "1",
    rachaSlug: "default",
    type: "outros",
    titulo: "Atualizacoes de Sistema",
    tipo: "Atualizacoes de Sistema",
    mensagem: "Nova atualizacao no Fut7Pro",
    data: "15/06/2025 09:00",
    destino: "Todos",
    status: "enviado",
    enviadoPor: "SuperAdmin",
    lida: false,
  },
  {
    id: "2",
    rachaSlug: "default",
    type: "financeiro",
    titulo: "Cobranca/Financeiro",
    tipo: "Cobranca/Financeiro",
    mensagem: "Cobranca automatica mensal",
    data: "10/06/2025 10:00",
    destino: "Rachas Mensal",
    status: "enviado",
    enviadoPor: "SuperAdmin",
    lida: false,
  },
  {
    id: "3",
    rachaSlug: "default",
    type: "superadmin",
    titulo: "Onboarding/Boas-vindas",
    tipo: "Onboarding/Boas-vindas",
    mensagem: "Boas-vindas ao novo presidente",
    data: "08/06/2025 08:30",
    destino: "Novos Admin",
    status: "enviado",
    enviadoPor: "SuperAdmin",
    lida: false,
  },
  {
    id: "4",
    rachaSlug: "default",
    type: "alerta",
    titulo: "Gamificacao e Conquistas",
    tipo: "Gamificacao e Conquistas",
    mensagem: "Seu racha bateu recorde de assiduidade!",
    data: "05/06/2025 11:20",
    destino: "Todos",
    status: "enviado",
    enviadoPor: "SuperAdmin",
    lida: false,
  },
  {
    id: "5",
    rachaSlug: "default",
    type: "novidade",
    titulo: "Promocoes e Ofertas",
    tipo: "Promocoes e Ofertas",
    mensagem: "Semana do Futebol: Planos com 10% OFF!",
    data: "01/06/2025 13:00",
    destino: "Todos",
    status: "enviado",
    enviadoPor: "SuperAdmin",
    lida: false,
  },
];
