import type { RankingAtleta } from "@/types/estatisticas";

export const rankingQuadrimestral: RankingAtleta[] = [
  {
    id: 1,
    nome: "Matheus Silva",
    slug: "matheus-silva",
    foto: "/images/jogadores/jogador_padrao_01.jpg",
    pontos: 350,
    jogos: 18,
    vitorias: 11,
    empates: 4,
    derrotas: 3,
    gols: 14,
    assistencias: 9,
  },
  {
    id: 2,
    nome: "Lucas Rocha",
    slug: "lucas-rocha",
    foto: "/images/jogadores/jogador_padrao_02.jpg",
    pontos: 288,
    jogos: 15,
    vitorias: 7,
    empates: 5,
    derrotas: 3,
    gols: 8,
    assistencias: 7,
  },
  {
    id: 3,
    nome: "João Pedro",
    slug: "joao-pedro",
    foto: "/images/jogadores/jogador_padrao_03.jpg",
    pontos: 255,
    jogos: 12,
    vitorias: 6,
    empates: 3,
    derrotas: 3,
    gols: 7,
    assistencias: 5,
  },
  {
    id: 4,
    nome: "Carlos Lima",
    slug: "carlos-lima",
    foto: "/images/jogadores/jogador_padrao_04.jpg",
    pontos: 240,
    jogos: 12,
    vitorias: 5,
    empates: 4,
    derrotas: 3,
    gols: 6,
    assistencias: 4,
  },
  {
    id: 5,
    nome: "Rafael Costa",
    slug: "rafael-costa",
    foto: "/images/jogadores/jogador_padrao_05.jpg",
    pontos: 230,
    jogos: 11,
    vitorias: 5,
    empates: 3,
    derrotas: 3,
    gols: 5,
    assistencias: 6,
  },
];
