export const usuarioLogadoMock = {
  id: "user-1",
  nome: "Usuário",
  email: "user@example.com",
  foto: "/images/jogadores/default.png",
  slug: "usuario",
  apelido: "User",
  posicao: "Meia",
  status: "Ativo",
  mensalista: false,
  ultimaPartida: "2025-01-01",
  totalJogos: 0,
  estatisticas: {
    historico: {
      jogos: 0,
      gols: 0,
      assistencias: 0,
      campeaoDia: 0,
      mediaVitorias: 0,
      pontuacao: 0,
    },
    anual: {},
  },
  historico: [],
  conquistas: { titulosGrandesTorneios: [], titulosAnuais: [], titulosQuadrimestrais: [] },
};
