export const campeoesAno = [
  // ================= 2025 ===================
  {
    titulo: "Melhor do Ano",
    nome: "Matheus Silva",
    slug: "matheus-silva",
    image: "/images/jogadores/jogador_padrao_01.jpg",
    valor: "1320 pontos",
    icone: "🏆",
    href: "/estatisticas/ranking-geral",
    temporario: true,
    ano: 2025,
  },
  {
    titulo: "Artilheiro do Ano",
    nome: "Matheus Silva",
    slug: "matheus-silva",
    image: "/images/jogadores/jogador_padrao_01.jpg",
    valor: "45 gols",
    icone: "🏆",
    href: "/estatisticas/artilheiros",
    temporario: true,
    ano: 2025,
  },
  {
    titulo: "Maestro do Ano", // <--- ALTERADO AQUI
    nome: "Lucas Rocha",
    slug: "lucas-rocha",
    image: "/images/jogadores/jogador_padrao_02.jpg",
    valor: "30 assistências",
    icone: "/images/icons/chuteira-de-ouro.png", // <--- ALTERADO AQUI
    href: "/estatisticas/assistencias",
    temporario: true,
    ano: 2025,
  },
  {
    titulo: "Campeão do Ano",
    nome: "Time Fênix",
    slug: "time-fenix",
    image: "/images/times/time_padrao_01.png",
    valor: "68 pontos",
    icone: "🏆",
    href: "/estatisticas/classificacao-dos-times",
    temporario: true,
    ano: 2025,
  },

  // ================= 2024 ===================
  {
    titulo: "Melhor do Ano",
    nome: "Estrela Solitária",
    slug: "estrela-solitaria",
    image: "/images/jogadores/jogador_padrao_03.jpg",
    valor: "79 pontos",
    icone: "🏆",
    href: "/estatisticas/ranking-geral",
    temporario: false,
    ano: 2024,
  },
  {
    titulo: "Artilheiro do Ano",
    nome: "Matador X",
    slug: "matador-x",
    image: "/images/jogadores/jogador_padrao_04.jpg",
    valor: "27 gols",
    icone: "🏆",
    href: "/estatisticas/artilheiros",
    temporario: false,
    ano: 2024,
  },
  {
    titulo: "Maestro do Ano", // <--- ALTERADO AQUI
    nome: "Arthur Maia",
    slug: "arthur-maia",
    image: "/images/jogadores/jogador_padrao_05.jpg",
    valor: "18 assistências",
    icone: "/images/icons/chuteira-de-ouro.png", // <--- ALTERADO AQUI
    href: "/estatisticas/assistencias",
    temporario: false,
    ano: 2024,
  },
  {
    titulo: "Campeão do Ano",
    nome: "Time Relâmpago",
    slug: "time-relampago",
    image: "/images/times/time_padrao_02.png",
    valor: "62 pontos",
    icone: "🏆",
    href: "/estatisticas/classificacao-dos-times",
    temporario: false,
    ano: 2024,
  },

  // ================= 2023 ===================
  {
    titulo: "Melhor do Ano",
    nome: "Lenda Viva",
    slug: "lenda-viva",
    image: "/images/jogadores/jogador_padrao_05.jpg",
    valor: "92 pontos",
    icone: "🏆",
    href: "/estatisticas/ranking-geral",
    temporario: false,
    ano: 2023,
  },
  {
    titulo: "Artilheiro do Ano",
    nome: "Canhão de Ouro",
    slug: "canhao-de-ouro",
    image: "/images/jogadores/jogador_padrao_06.jpg",
    valor: "34 gols",
    icone: "🏆",
    href: "/estatisticas/artilheiros",
    temporario: false,
    ano: 2023,
  },
  {
    titulo: "Maestro do Ano", // <--- ALTERADO AQUI
    nome: "Jean Passador",
    slug: "jean-passador",
    image: "/images/jogadores/jogador_padrao_07.jpg",
    valor: "25 assistências",
    icone: "/images/icons/chuteira-de-ouro.png", // <--- ALTERADO AQUI
    href: "/estatisticas/assistencias",
    temporario: false,
    ano: 2023,
  },
  {
    titulo: "Campeão do Ano",
    nome: "Time Raiz",
    slug: "time-raiz",
    image: "/images/times/time_padrao_03.png",
    valor: "70 pontos",
    icone: "🏆",
    href: "/estatisticas/classificacao-dos-times",
    temporario: false,
    ano: 2023,
  },
];
