import type { RankingAtleta } from "@/types/estatisticas";

export const melhoresGoleirosAnual: Record<number, RankingAtleta[]> = {
  2025: [
    {
      id: 12,
      nome: "Rafael Goleiro",
      slug: "rafael-goleiro",
      foto: "/images/jogadores/jogador_padrao_12.jpg",
      pontos: 390,
      jogos: 45,
      vitorias: 0,
      empates: 0,
      derrotas: 0,
      gols: 0,
      assistencias: 0,
    },
    {
      id: 13,
      nome: "Carlos Paredão",
      slug: "carlos-paredao",
      foto: "/images/jogadores/jogador_padrao_13.jpg",
      pontos: 340,
      jogos: 41,
      vitorias: 0,
      empates: 0,
      derrotas: 0,
      gols: 0,
      assistencias: 0,
    },
    {
      id: 14,
      nome: "Tiago Seguro",
      slug: "tiago-seguro",
      foto: "/images/jogadores/jogador_padrao_14.jpg",
      pontos: 325,
      jogos: 39,
      vitorias: 0,
      empates: 0,
      derrotas: 0,
      gols: 0,
      assistencias: 0,
    },
  ],
  2024: [
    {
      id: 12,
      nome: "Lucas Muralha",
      slug: "lucas-muralha",
      foto: "/images/jogadores/jogador_padrao_15.jpg",
      pontos: 300,
      jogos: 37,
      vitorias: 0,
      empates: 0,
      derrotas: 0,
      gols: 0,
      assistencias: 0,
    },
  ],
};
