import type { RankingAtleta } from "@/types/estatisticas";

export const melhoresMeiasAnual: Record<number, RankingAtleta[]> = {
  2025: [
    {
      id: 4,
      nome: "Diego Meia",
      slug: "diego-meia",
      foto: "/images/jogadores/jogador_padrao_04.jpg",
      pontos: 510,
      jogos: 48,
      vitorias: 0,
      empates: 0,
      derrotas: 0,
      gols: 0,
      assistencias: 0,
    },
    {
      id: 5,
      nome: "Arthur Maestro",
      slug: "arthur-maestro",
      foto: "/images/jogadores/jogador_padrao_05.jpg",
      pontos: 425,
      jogos: 40,
      vitorias: 0,
      empates: 0,
      derrotas: 0,
      gols: 0,
      assistencias: 0,
    },
    {
      id: 6,
      nome: "Renato Organizador",
      slug: "renato-organizador",
      foto: "/images/jogadores/jogador_padrao_06.jpg",
      pontos: 390,
      jogos: 38,
      vitorias: 0,
      empates: 0,
      derrotas: 0,
      gols: 0,
      assistencias: 0,
    },
  ],
  2024: [
    {
      id: 4,
      nome: "Marcelo Visionário",
      slug: "marcelo-visionario",
      foto: "/images/jogadores/jogador_padrao_07.jpg",
      pontos: 430,
      jogos: 41,
      vitorias: 0,
      empates: 0,
      derrotas: 0,
      gols: 0,
      assistencias: 0,
    },
  ],
};
