import type { RankingAtleta } from "@/types/estatisticas";

export const rankingAnuais: Record<number, RankingAtleta[]> = {
  2025: [
    {
      id: "1", // Corrigido para string
      nome: "Matheus Silva",
      slug: "matheus-silva",
      foto: "/images/jogadores/jogador_padrao_01.jpg",
      pontos: 1100,
      jogos: 50,
      vitorias: 28,
      empates: 12,
      derrotas: 10,
      gols: 42,
      assistencias: 21,
    },
    {
      id: "2",
      nome: "Lucas Rocha",
      slug: "lucas-rocha",
      foto: "/images/jogadores/jogador_padrao_02.jpg",
      pontos: 950,
      jogos: 44,
      vitorias: 20,
      empates: 15,
      derrotas: 9,
      gols: 28,
      assistencias: 13,
    },
    {
      id: "3",
      nome: "João Pedro",
      slug: "joao-pedro",
      foto: "/images/jogadores/jogador_padrao_03.jpg",
      pontos: 870,
      jogos: 40,
      vitorias: 18,
      empates: 12,
      derrotas: 10,
      gols: 21,
      assistencias: 10,
    },
  ],
  2024: [
    {
      id: "1",
      nome: "Pedro Lima",
      slug: "pedro-lima",
      foto: "/images/jogadores/jogador_padrao_04.jpg",
      pontos: 980,
      jogos: 46,
      vitorias: 22,
      empates: 12,
      derrotas: 12,
      gols: 34,
      assistencias: 17,
    },
    {
      id: "2",
      nome: "André Souza",
      slug: "andre-souza",
      foto: "/images/jogadores/jogador_padrao_05.jpg",
      pontos: 820,
      jogos: 40,
      vitorias: 16,
      empates: 12,
      derrotas: 12,
      gols: 27,
      assistencias: 9,
    },
  ],
};
