import type { RankingAtleta } from "@/types/estatisticas";

export const melhoresZagueirosAnual: Record<number, RankingAtleta[]> = {
  2025: [
    {
      id: 7,
      nome: "Bruno Zaga",
      slug: "bruno-zaga",
      foto: "/images/jogadores/jogador_padrao_08.jpg",
      pontos: 430,
      jogos: 46,
      vitorias: 0,
      empates: 0,
      derrotas: 0,
      gols: 0,
      assistencias: 0,
    },
    {
      id: 8,
      nome: "Eduardo Muralha",
      slug: "eduardo-muralha",
      foto: "/images/jogadores/jogador_padrao_09.jpg",
      pontos: 380,
      jogos: 41,
      vitorias: 0,
      empates: 0,
      derrotas: 0,
      gols: 0,
      assistencias: 0,
    },
    {
      id: 9,
      nome: "Luís Defensor",
      slug: "luis-defensor",
      foto: "/images/jogadores/jogador_padrao_10.jpg",
      pontos: 345,
      jogos: 38,
      vitorias: 0,
      empates: 0,
      derrotas: 0,
      gols: 0,
      assistencias: 0,
    },
  ],
  2024: [
    {
      id: 7,
      nome: "Vitor Fortão",
      slug: "vitor-fortao",
      foto: "/images/jogadores/jogador_padrao_11.jpg",
      pontos: 300,
      jogos: 35,
      vitorias: 0,
      empates: 0,
      derrotas: 0,
      gols: 0,
      assistencias: 0,
    },
  ],
};
