import type { TimeDoDia, DestaqueDoDia } from "@/types/partida";

export const timesDoDiaMock: TimeDoDia[] = [
  {
    id: "1",
    nome: "Leões",
    logo: "/images/times/time_padrao_01.png",
    cor: "#FFD700",
    jogadores: [
      {
        id: "1",
        nome: "João",
        apelido: "J. Goleiro",
        foto: "/images/jogadores/jogador_padrao_01.jpg",
        posicao: "Goleiro",
        status: "titular",
      },
      {
        id: "2",
        nome: "Carlos",
        apelido: "Carlão",
        foto: "/images/jogadores/jogador_padrao_02.jpg",
        posicao: "Zagueiro",
        status: "titular",
      },
      {
        id: "3",
        nome: "Marcos",
        apelido: "Marcão",
        foto: "/images/jogadores/jogador_padrao_03.jpg",
        posicao: "Meia",
        status: "titular",
      },
      {
        id: "4",
        nome: "Pedro",
        apelido: "Pedrinho",
        foto: "/images/jogadores/jogador_padrao_04.jpg",
        posicao: "Atacante",
        status: "titular",
      },
      {
        id: "5",
        nome: "Lucas",
        apelido: "Luquinhas",
        foto: "/images/jogadores/jogador_padrao_05.jpg",
        posicao: "Atacante",
        status: "titular",
      },
      {
        id: "6",
        nome: "Ricardo",
        apelido: "Rick",
        foto: "/images/jogadores/jogador_padrao_06.jpg",
        posicao: "Meia",
        status: "titular",
      },
      {
        id: "7",
        nome: "Vinícius",
        apelido: "Vini",
        foto: "/images/jogadores/jogador_padrao_07.jpg",
        posicao: "Zagueiro",
        status: "titular",
      },
    ],
  },
  {
    id: "2",
    nome: "Tigres",
    logo: "/images/times/time_padrao_02.png",
    cor: "#F59E42",
    jogadores: [
      {
        id: "8",
        nome: "Felipe",
        apelido: "Felipão",
        foto: "/images/jogadores/jogador_padrao_08.jpg",
        posicao: "Goleiro",
        status: "titular",
      },
      {
        id: "9",
        nome: "Bruno",
        apelido: "Brunão",
        foto: "/images/jogadores/jogador_padrao_09.jpg",
        posicao: "Zagueiro",
        status: "titular",
      },
      {
        id: "10",
        nome: "Henrique",
        apelido: "Henricão",
        foto: "/images/jogadores/jogador_padrao_10.jpg",
        posicao: "Meia",
        status: "titular",
      },
      {
        id: "11",
        nome: "Daniel",
        apelido: "Dani",
        foto: "/images/jogadores/jogador_padrao_11.jpg",
        posicao: "Atacante",
        status: "titular",
      },
      {
        id: "12",
        nome: "Rafael",
        apelido: "Rafinha",
        foto: "/images/jogadores/jogador_padrao_12.jpg",
        posicao: "Atacante",
        status: "titular",
      },
      {
        id: "13",
        nome: "Matheus",
        apelido: "Matt",
        foto: "/images/jogadores/jogador_padrao_13.jpg",
        posicao: "Meia",
        status: "titular",
      },
      {
        id: "14",
        nome: "César",
        apelido: "Cesinha",
        foto: "/images/jogadores/jogador_padrao_14.jpg",
        posicao: "Zagueiro",
        status: "titular",
      },
    ],
  },
  {
    id: "3",
    nome: "Águias",
    logo: "/images/times/time_padrao_03.png",
    cor: "#2563EB",
    jogadores: [
      {
        id: "15",
        nome: "Rafael",
        apelido: "Rafa",
        foto: "/images/jogadores/jogador_padrao_15.jpg",
        posicao: "Goleiro",
        status: "titular",
      },
      {
        id: "16",
        nome: "Ricardo",
        apelido: "Rick",
        foto: "/images/jogadores/jogador_padrao_16.jpg",
        posicao: "Zagueiro",
        status: "titular",
      },
      {
        id: "17",
        nome: "Thiago",
        apelido: "Thiaguinho",
        foto: "/images/jogadores/jogador_padrao_17.jpg",
        posicao: "Meia",
        status: "titular",
      },
      {
        id: "18",
        nome: "Bruno",
        apelido: "Bruninho",
        foto: "/images/jogadores/jogador_padrao_18.jpg",
        posicao: "Atacante",
        status: "titular",
      },
      {
        id: "19",
        nome: "Samuel",
        apelido: "Samuca",
        foto: "/images/jogadores/jogador_padrao_19.jpg",
        posicao: "Atacante",
        status: "titular",
      },
      {
        id: "20",
        nome: "João Paulo",
        apelido: "JP",
        foto: "/images/jogadores/jogador_padrao_20.jpg",
        posicao: "Meia",
        status: "titular",
      },
      {
        id: "21",
        nome: "Eduardo",
        apelido: "Dudu",
        foto: "/images/jogadores/jogador_padrao_21.jpg",
        posicao: "Zagueiro",
        status: "titular",
      },
    ],
  },
  {
    id: "4",
    nome: "Furacão",
    logo: "/images/times/time_padrao_04.png",
    cor: "#22C55E",
    jogadores: [
      {
        id: "22",
        nome: "Lucas",
        apelido: "Barros",
        foto: "/images/jogadores/jogador_padrao_22.jpg",
        posicao: "Goleiro",
        status: "titular",
      },
      {
        id: "23",
        nome: "Matheus",
        apelido: "Matheuzinho",
        foto: "/images/jogadores/jogador_padrao_23.jpg",
        posicao: "Zagueiro",
        status: "titular",
      },
      {
        id: "24",
        nome: "Julio",
        apelido: "Julinho",
        foto: "/images/jogadores/jogador_padrao_01.jpg",
        posicao: "Meia",
        status: "titular",
      },
      {
        id: "25",
        nome: "Bruno Costa",
        apelido: "Costinha",
        foto: "/images/jogadores/jogador_padrao_02.jpg",
        posicao: "Atacante",
        status: "titular",
      },
      {
        id: "26",
        nome: "Diego",
        apelido: "Diegão",
        foto: "/images/jogadores/jogador_padrao_03.jpg",
        posicao: "Atacante",
        status: "titular",
      },
      {
        id: "27",
        nome: "Igor",
        apelido: "Igão",
        foto: "/images/jogadores/jogador_padrao_04.jpg",
        posicao: "Meia",
        status: "titular",
      },
      {
        id: "28",
        nome: "Wesley",
        apelido: "Wes",
        foto: "/images/jogadores/jogador_padrao_05.jpg",
        posicao: "Zagueiro",
        status: "titular",
      },
    ],
  },
];

// Destaques do Dia (exemplo, pode ajustar conforme admin definir após os jogos)
export const destaquesDoDiaMock: DestaqueDoDia[] = [
  { tipo: "Goleiro", jogadorId: "1", timeId: "1" },
  { tipo: "Zagueiro", jogadorId: "2", timeId: "1" },
  { tipo: "Meia", jogadorId: "3", timeId: "1" },
  { tipo: "Atacante", jogadorId: "11", timeId: "2" },
  { tipo: "Artilheiro", jogadorId: "11", timeId: "2" },
  { tipo: "Maestro", jogadorId: "3", timeId: "1" },
];
