export type Jogador = {
  id: string;
  nome: string;
  imagem: string;
  posicao: string;
  gols: number;
  pontos: number;
};

export const mockJogadores: Jogador[] = [
  {
    id: "jogador01",
    nome: "João Henrique",
    imagem: "/images/jogadores/jogador01.png",
    posicao: "Atacante",
    gols: 20,
    pontos: 341,
  },
  {
    id: "jogador02",
    nome: "Carlos Lima",
    imagem: "/images/jogadores/jogador02.png",
    posicao: "Meia",
    gols: 13,
    pontos: 146,
  },
  {
    id: "jogador03",
    nome: "Pedro Silva",
    imagem: "/images/jogadores/jogador03.png",
    posicao: "Atacante",
    gols: 2,
    pontos: 193,
  },
  {
    id: "jogador04",
    nome: "Lucas Souza",
    imagem: "/images/jogadores/jogador04.png",
    posicao: "Goleiro",
    gols: 14,
    pontos: 331,
  },
  {
    id: "jogador05",
    nome: "André Martins",
    imagem: "/images/jogadores/jogador05.png",
    posicao: "Goleiro",
    gols: 15,
    pontos: 343,
  },
  {
    id: "jogador06",
    nome: "Fernando Rocha",
    imagem: "/images/jogadores/jogador06.png",
    posicao: "Zagueiro",
    gols: 18,
    pontos: 278,
  },
  {
    id: "jogador07",
    nome: "Bruno Costa",
    imagem: "/images/jogadores/jogador07.png",
    posicao: "Goleiro",
    gols: 2,
    pontos: 141,
  },
  {
    id: "jogador08",
    nome: "Felipe Alves",
    imagem: "/images/jogadores/jogador08.png",
    posicao: "Meia",
    gols: 19,
    pontos: 292,
  },
  {
    id: "jogador09",
    nome: "Rafael Dias",
    imagem: "/images/jogadores/jogador09.png",
    posicao: "Meia",
    gols: 11,
    pontos: 208,
  },
  {
    id: "jogador10",
    nome: "Daniel Barbosa",
    imagem: "/images/jogadores/jogador10.png",
    posicao: "Goleiro",
    gols: 8,
    pontos: 163,
  },
  {
    id: "jogador11",
    nome: "Tiago Gomes",
    imagem: "/images/jogadores/jogador11.png",
    posicao: "Atacante",
    gols: 4,
    pontos: 230,
  },
  {
    id: "jogador12",
    nome: "Victor Leite",
    imagem: "/images/jogadores/jogador12.png",
    posicao: "Atacante",
    gols: 5,
    pontos: 294,
  },
  {
    id: "jogador13",
    nome: "Matheus Freitas",
    imagem: "/images/jogadores/jogador13.png",
    posicao: "Goleiro",
    gols: 20,
    pontos: 241,
  },
  {
    id: "jogador14",
    nome: "Ricardo Moura",
    imagem: "/images/jogadores/jogador14.png",
    posicao: "Zagueiro",
    gols: 14,
    pontos: 153,
  },
  {
    id: "jogador15",
    nome: "Eduardo Cunha",
    imagem: "/images/jogadores/jogador15.png",
    posicao: "Zagueiro",
    gols: 4,
    pontos: 299,
  },
  {
    id: "jogador16",
    nome: "Marcelo Santos",
    imagem: "/images/jogadores/jogador16.png",
    posicao: "Zagueiro",
    gols: 18,
    pontos: 115,
  },
  {
    id: "jogador17",
    nome: "Leonardo Rocha",
    imagem: "/images/jogadores/jogador17.png",
    posicao: "Zagueiro",
    gols: 1,
    pontos: 273,
  },
  {
    id: "jogador18",
    nome: "Paulo Andrade",
    imagem: "/images/jogadores/jogador18.png",
    posicao: "Atacante",
    gols: 3,
    pontos: 160,
  },
  {
    id: "jogador19",
    nome: "Fábio Rezende",
    imagem: "/images/jogadores/jogador19.png",
    posicao: "Meia",
    gols: 18,
    pontos: 125,
  },
  {
    id: "jogador20",
    nome: "Gustavo Pinto",
    imagem: "/images/jogadores/jogador20.png",
    posicao: "Zagueiro",
    gols: 20,
    pontos: 297,
  },
  {
    id: "jogador21",
    nome: "Diego Ramos",
    imagem: "/images/jogadores/jogador21.png",
    posicao: "Zagueiro",
    gols: 0,
    pontos: 285,
  },
  {
    id: "jogador22",
    nome: "Alex Teixeira",
    imagem: "/images/jogadores/jogador22.png",
    posicao: "Zagueiro",
    gols: 2,
    pontos: 144,
  },
  {
    id: "jogador23",
    nome: "Gabriel Torres",
    imagem: "/images/jogadores/jogador23.png",
    posicao: "Atacante",
    gols: 0,
    pontos: 139,
  },
  {
    id: "jogador24",
    nome: "Henrique Ribeiro",
    imagem: "/images/jogadores/jogador24.png",
    posicao: "Atacante",
    gols: 11,
    pontos: 176,
  },
];
