export const melhoresPorPosicao = [
  // 🔶 2025 — ORDEM CORRETA: Atacante, Meia, Zagueiro, Goleiro
  {
    posicao: "Atacante do Ano",
    nome: "Matador Alfa",
    slug: "matador-alfa",
    image: "/images/jogadores/jogador_padrao_03.jpg",
    valor: "78 pontos",
    icone: "🏆",
    href: "/estatisticas/melhores-por-posicao/atacante",
    temporario: true,
    ano: 2025,
  },
  {
    posicao: "Meia do Ano",
    nome: "Camisa 10",
    slug: "camisa-10",
    image: "/images/jogadores/jogador_padrao_04.jpg",
    valor: "67 pontos",
    icone: "🏆",
    href: "/estatisticas/melhores-por-posicao/meia",
    temporario: true,
    ano: 2025,
  },
  {
    posicao: "Zagueiro do Ano",
    nome: "Muralha Beta",
    slug: "muralha-beta",
    image: "/images/jogadores/jogador_padrao_05.jpg",
    valor: "62 pontos",
    icone: "🏆",
    href: "/estatisticas/melhores-por-posicao/zagueiro",
    temporario: true,
    ano: 2025,
  },
  {
    posicao: "Goleiro do Ano",
    nome: "Paredão",
    slug: "paredao",
    image: "/images/jogadores/jogador_padrao_06.jpg",
    valor: "60 pontos",
    icone: "/images/icons/luva-de-ouro.png", // <--- Atualizado!
    href: "/estatisticas/melhores-por-posicao/goleiro",
    temporario: true,
    ano: 2025,
  },

  // 🔷 2024
  {
    posicao: "Atacante do Ano",
    nome: "Canhoto Rápido",
    slug: "canhoto-rapido",
    image: "/images/jogadores/jogador_padrao_07.jpg",
    valor: "72 pontos",
    icone: "🏆",
    href: "/estatisticas/melhores-por-posicao/atacante",
    temporario: false,
    ano: 2024,
  },
  {
    posicao: "Meia do Ano",
    nome: "Criador Z",
    slug: "criador-z",
    image: "/images/jogadores/jogador_padrao_08.jpg",
    valor: "61 pontos",
    icone: "🏆",
    href: "/estatisticas/melhores-por-posicao/meia",
    temporario: false,
    ano: 2024,
  },
  {
    posicao: "Zagueiro do Ano",
    nome: "Murilo",
    slug: "murilo",
    image: "/images/jogadores/jogador_padrao_09.jpg",
    valor: "58 pontos",
    icone: "🏆",
    href: "/estatisticas/melhores-por-posicao/zagueiro",
    temporario: false,
    ano: 2024,
  },
  {
    posicao: "Goleiro do Ano",
    nome: "Mão Santa",
    slug: "mao-santa",
    image: "/images/jogadores/jogador_padrao_10.jpg",
    valor: "55 pontos",
    icone: "/images/icons/luva-de-ouro.png", // <--- Atualizado!
    href: "/estatisticas/melhores-por-posicao/goleiro",
    temporario: false,
    ano: 2024,
  },

  // 🟢 2023
  {
    posicao: "Atacante do Ano",
    nome: "Veterano Gol",
    slug: "veterano-gol",
    image: "/images/jogadores/jogador_padrao_11.jpg",
    valor: "69 pontos",
    icone: "🏆",
    href: "/estatisticas/melhores-por-posicao/atacante",
    temporario: false,
    ano: 2023,
  },
  {
    posicao: "Meia do Ano",
    nome: "Maestro",
    slug: "maestro",
    image: "/images/jogadores/jogador_padrao_12.jpg",
    valor: "57 pontos",
    icone: "🏆",
    href: "/estatisticas/melhores-por-posicao/meia",
    temporario: false,
    ano: 2023,
  },
  {
    posicao: "Zagueiro do Ano",
    nome: "Pantera",
    slug: "pantera",
    image: "/images/jogadores/jogador_padrao_13.jpg",
    valor: "50 pontos",
    icone: "🏆",
    href: "/estatisticas/melhores-por-posicao/zagueiro",
    temporario: false,
    ano: 2023,
  },
  {
    posicao: "Goleiro do Ano",
    nome: "Defensor Supremo",
    slug: "defensor-supremo",
    image: "/images/jogadores/jogador_padrao_14.jpg",
    valor: "47 pontos",
    icone: "/images/icons/luva-de-ouro.png", // <--- Atualizado!
    href: "/estatisticas/melhores-por-posicao/goleiro",
    temporario: false,
    ano: 2023,
  },
];
