import type { Partida } from "@/types/partida";

export const partidasMock: Partida[] = [
  {
    id: "1",
    timeA: "Leões",
    timeB: "Tigres",
    golsTimeA: 2,
    golsTimeB: 1,
    finalizada: true,
    data: "2024-01-15",
    local: "Campo Principal",
    gols: [
      {
        id: "1",
        jogador: "João",
        time: "Leões",
        minuto: 15,
        tipo: "normal",
      },
      {
        id: "2",
        jogador: "Carlos",
        time: "Leões",
        minuto: 32,
        tipo: "normal",
      },
      {
        id: "3",
        jogador: "Daniel",
        time: "Tigres",
        minuto: 45,
        tipo: "penalti",
      },
    ],
    assistencias: [
      {
        id: "1",
        jogador: "Marcos",
        time: "Leões",
        minuto: 15,
      },
      {
        id: "2",
        jogador: "Pedro",
        time: "Leões",
        minuto: 32,
      },
    ],
  },
  {
    id: "2",
    timeA: "Águias",
    timeB: "Furacão",
    golsTimeA: 0,
    golsTimeB: 3,
    finalizada: true,
    data: "2024-01-15",
    local: "Campo Secundário",
    gols: [
      {
        id: "4",
        jogador: "Bruno Costa",
        time: "Furacão",
        minuto: 8,
        tipo: "normal",
      },
      {
        id: "5",
        jogador: "Diego",
        time: "Furacão",
        minuto: 25,
        tipo: "normal",
      },
      {
        id: "6",
        jogador: "Igor",
        time: "Furacão",
        minuto: 52,
        tipo: "falta",
      },
    ],
    assistencias: [
      {
        id: "3",
        jogador: "Julio",
        time: "Furacão",
        minuto: 8,
      },
      {
        id: "4",
        jogador: "Matheus",
        time: "Furacão",
        minuto: 25,
      },
      {
        id: "5",
        jogador: "Wesley",
        time: "Furacão",
        minuto: 52,
      },
    ],
  },
  {
    id: "3",
    timeA: "Hawks",
    timeB: "Panthers",
    golsTimeA: 1,
    golsTimeB: 1,
    finalizada: true,
    data: "2024-01-14",
    local: "Campo Principal",
    gols: [
      {
        id: "7",
        jogador: "Rafael",
        time: "Hawks",
        minuto: 12,
        tipo: "normal",
      },
      {
        id: "8",
        jogador: "Thiago",
        time: "Panthers",
        minuto: 38,
        tipo: "normal",
      },
    ],
    assistencias: [
      {
        id: "6",
        jogador: "Bruno",
        time: "Hawks",
        minuto: 12,
      },
      {
        id: "7",
        jogador: "Henrique",
        time: "Panthers",
        minuto: 38,
      },
    ],
  },
  {
    id: "4",
    timeA: "Wolves",
    timeB: "Trovão",
    golsTimeA: 4,
    golsTimeB: 2,
    finalizada: true,
    data: "2024-01-13",
    local: "Campo Secundário",
    gols: [
      {
        id: "9",
        jogador: "Samuel",
        time: "Wolves",
        minuto: 5,
        tipo: "normal",
      },
      {
        id: "10",
        jogador: "João Paulo",
        time: "Wolves",
        minuto: 18,
        tipo: "normal",
      },
      {
        id: "11",
        jogador: "Eduardo",
        time: "Wolves",
        minuto: 33,
        tipo: "normal",
      },
      {
        id: "12",
        jogador: "Lucas",
        time: "Wolves",
        minuto: 47,
        tipo: "normal",
      },
      {
        id: "13",
        jogador: "Matheus",
        time: "Trovão",
        minuto: 22,
        tipo: "normal",
      },
      {
        id: "14",
        jogador: "Julio",
        time: "Trovão",
        minuto: 41,
        tipo: "normal",
      },
    ],
    assistencias: [
      {
        id: "8",
        jogador: "Eduardo",
        time: "Wolves",
        minuto: 5,
      },
      {
        id: "9",
        jogador: "Samuel",
        time: "Wolves",
        minuto: 18,
      },
      {
        id: "10",
        jogador: "João Paulo",
        time: "Wolves",
        minuto: 33,
      },
      {
        id: "11",
        jogador: "Samuel",
        time: "Wolves",
        minuto: 47,
      },
      {
        id: "12",
        jogador: "Bruno Costa",
        time: "Trovão",
        minuto: 22,
      },
      {
        id: "13",
        jogador: "Diego",
        time: "Trovão",
        minuto: 41,
      },
    ],
  },
];
