// src/components/sorteio/mockParticipantes.ts

import type { Participante } from "@/types/sorteio";

const hoje = new Date().toISOString();

export const mockParticipantes: Participante[] = [
  // BLOCO 1 (jogador_padrao_01 a jogador_padrao_07)
  {
    id: "1",
    nome: "Goleiro 1",
    slug: "goleiro-1",
    foto: "/images/jogadores/jogador_padrao_01.jpg",
    posicao: "GOL",
    rankingPontos: 78,
    vitorias: 6,
    gols: 0,
    assistencias: 2,
    estrelas: { estrelas: 4, atualizadoEm: hoje, adminId: "1" },
    mensalista: true,
  },
  {
    id: "2",
    nome: "Zagueiro 1",
    slug: "zagueiro-1",
    foto: "/images/jogadores/jogador_padrao_02.jpg",
    posicao: "ZAG",
    rankingPontos: 74,
    vitorias: 7,
    gols: 1,
    assistencias: 1,
    estrelas: { estrelas: 3, atualizadoEm: hoje, adminId: "1" },
    mensalista: true,
  },
  {
    id: "3",
    nome: "Zagueiro 2",
    slug: "zagueiro-2",
    foto: "/images/jogadores/jogador_padrao_03.jpg",
    posicao: "ZAG",
    rankingPontos: 76,
    vitorias: 5,
    gols: 0,
    assistencias: 2,
    estrelas: { estrelas: 3, atualizadoEm: hoje, adminId: "1" },
    mensalista: true,
  },
  {
    id: "4",
    nome: "Meia 1",
    slug: "meia-1",
    foto: "/images/jogadores/jogador_padrao_04.jpg",
    posicao: "MEI",
    rankingPontos: 82,
    vitorias: 8,
    gols: 2,
    assistencias: 5,
    estrelas: { estrelas: 4, atualizadoEm: hoje, adminId: "1" },
    mensalista: true,
  },
  {
    id: "5",
    nome: "Meia 2",
    slug: "meia-2",
    foto: "/images/jogadores/jogador_padrao_05.jpg",
    posicao: "MEI",
    rankingPontos: 80,
    vitorias: 7,
    gols: 3,
    assistencias: 4,
    estrelas: { estrelas: 4, atualizadoEm: hoje, adminId: "1" },
    mensalista: true,
  },
  {
    id: "6",
    nome: "Atacante 1",
    slug: "atacante-1",
    foto: "/images/jogadores/jogador_padrao_06.jpg",
    posicao: "ATA",
    rankingPontos: 88,
    vitorias: 10,
    gols: 11,
    assistencias: 3,
    estrelas: { estrelas: 5, atualizadoEm: hoje, adminId: "1" },
    mensalista: true,
  },
  {
    id: "7",
    nome: "Atacante 2",
    slug: "atacante-2",
    foto: "/images/jogadores/jogador_padrao_07.jpg",
    posicao: "ATA",
    rankingPontos: 85,
    vitorias: 9,
    gols: 9,
    assistencias: 4,
    estrelas: { estrelas: 4, atualizadoEm: hoje, adminId: "1" },
    mensalista: true,
  },

  // BLOCO 2 (jogador_padrao_08 a jogador_padrao_14)
  {
    id: "8",
    nome: "Goleiro 2",
    slug: "goleiro-2",
    foto: "/images/jogadores/jogador_padrao_08.jpg",
    posicao: "GOL",
    rankingPontos: 70,
    vitorias: 4,
    gols: 0,
    assistencias: 2,
    estrelas: { estrelas: 3, atualizadoEm: hoje, adminId: "1" },
    mensalista: true,
  },
  {
    id: "9",
    nome: "Zagueiro 3",
    slug: "zagueiro-3",
    foto: "/images/jogadores/jogador_padrao_09.jpg",
    posicao: "ZAG",
    rankingPontos: 72,
    vitorias: 6,
    gols: 0,
    assistencias: 2,
    estrelas: { estrelas: 3, atualizadoEm: hoje, adminId: "1" },
    mensalista: true,
  },
  {
    id: "10",
    nome: "Zagueiro 4",
    slug: "zagueiro-4",
    foto: "/images/jogadores/jogador_padrao_10.jpg",
    posicao: "ZAG",
    rankingPontos: 75,
    vitorias: 7,
    gols: 2,
    assistencias: 3,
    estrelas: { estrelas: 4, atualizadoEm: hoje, adminId: "1" },
    mensalista: true,
  },
  {
    id: "11",
    nome: "Meia 3",
    slug: "meia-3",
    foto: "/images/jogadores/jogador_padrao_11.jpg",
    posicao: "MEI",
    rankingPontos: 79,
    vitorias: 6,
    gols: 3,
    assistencias: 3,
    estrelas: { estrelas: 3, atualizadoEm: hoje, adminId: "1" },
    mensalista: true,
  },
  {
    id: "12",
    nome: "Meia 4",
    slug: "meia-4",
    foto: "/images/jogadores/jogador_padrao_12.jpg",
    posicao: "MEI",
    rankingPontos: 77,
    vitorias: 5,
    gols: 2,
    assistencias: 2,
    estrelas: { estrelas: 3, atualizadoEm: hoje, adminId: "1" },
    mensalista: true,
  },
  {
    id: "13",
    nome: "Atacante 3",
    slug: "atacante-3",
    foto: "/images/jogadores/jogador_padrao_13.jpg",
    posicao: "ATA",
    rankingPontos: 90,
    vitorias: 12,
    gols: 13,
    assistencias: 5,
    estrelas: { estrelas: 5, atualizadoEm: hoje, adminId: "1" },
    mensalista: true,
  },
  {
    id: "14",
    nome: "Atacante 4",
    slug: "atacante-4",
    foto: "/images/jogadores/jogador_padrao_14.jpg",
    posicao: "ATA",
    rankingPontos: 86,
    vitorias: 8,
    gols: 10,
    assistencias: 4,
    estrelas: { estrelas: 4, atualizadoEm: hoje, adminId: "1" },
    mensalista: true,
  },

  // BLOCO 3 (jogador_padrao_15 a jogador_padrao_21)
  {
    id: "15",
    nome: "Goleiro 3",
    slug: "goleiro-3",
    foto: "/images/jogadores/jogador_padrao_15.jpg",
    posicao: "GOL",
    rankingPontos: 68,
    vitorias: 3,
    gols: 0,
    assistencias: 1,
    estrelas: { estrelas: 3, atualizadoEm: hoje, adminId: "1" },
    mensalista: false,
  },
  {
    id: "16",
    nome: "Zagueiro 5",
    slug: "zagueiro-5",
    foto: "/images/jogadores/jogador_padrao_16.jpg",
    posicao: "ZAG",
    rankingPontos: 69,
    vitorias: 5,
    gols: 0,
    assistencias: 1,
    estrelas: { estrelas: 3, atualizadoEm: hoje, adminId: "1" },
    mensalista: false,
  },
  {
    id: "17",
    nome: "Zagueiro 6",
    slug: "zagueiro-6",
    foto: "/images/jogadores/jogador_padrao_17.jpg",
    posicao: "ZAG",
    rankingPontos: 73,
    vitorias: 7,
    gols: 2,
    assistencias: 2,
    estrelas: { estrelas: 4, atualizadoEm: hoje, adminId: "1" },
    mensalista: false,
  },
  {
    id: "18",
    nome: "Meia 5",
    slug: "meia-5",
    foto: "/images/jogadores/jogador_padrao_18.jpg",
    posicao: "MEI",
    rankingPontos: 76,
    vitorias: 6,
    gols: 2,
    assistencias: 4,
    estrelas: { estrelas: 3, atualizadoEm: hoje, adminId: "1" },
    mensalista: false,
  },
  {
    id: "19",
    nome: "Meia 6",
    slug: "meia-6",
    foto: "/images/jogadores/jogador_padrao_19.jpg",
    posicao: "MEI",
    rankingPontos: 75,
    vitorias: 4,
    gols: 1,
    assistencias: 2,
    estrelas: { estrelas: 3, atualizadoEm: hoje, adminId: "1" },
    mensalista: false,
  },
  {
    id: "20",
    nome: "Atacante 5",
    slug: "atacante-5",
    foto: "/images/jogadores/jogador_padrao_20.jpg",
    posicao: "ATA",
    rankingPontos: 89,
    vitorias: 10,
    gols: 12,
    assistencias: 4,
    estrelas: { estrelas: 5, atualizadoEm: hoje, adminId: "1" },
    mensalista: false,
  },
  {
    id: "21",
    nome: "Atacante 6",
    slug: "atacante-6",
    foto: "/images/jogadores/jogador_padrao_21.jpg",
    posicao: "ATA",
    rankingPontos: 84,
    vitorias: 7,
    gols: 8,
    assistencias: 3,
    estrelas: { estrelas: 4, atualizadoEm: hoje, adminId: "1" },
    mensalista: false,
  },

  // BLOCO 4 (jogador_padrao_22 a jogador_padrao_28)
  {
    id: "22",
    nome: "Goleiro 4",
    slug: "goleiro-4",
    foto: "/images/jogadores/jogador_padrao_22.jpg",
    posicao: "GOL",
    rankingPontos: 67,
    vitorias: 2,
    gols: 0,
    assistencias: 1,
    estrelas: { estrelas: 2, atualizadoEm: hoje, adminId: "1" },
    mensalista: false,
  },
  {
    id: "23",
    nome: "Zagueiro 7",
    slug: "zagueiro-7",
    foto: "/images/jogadores/jogador_padrao_23.jpg",
    posicao: "ZAG",
    rankingPontos: 68,
    vitorias: 3,
    gols: 1,
    assistencias: 2,
    estrelas: { estrelas: 3, atualizadoEm: hoje, adminId: "1" },
    mensalista: false,
  },
  {
    id: "24",
    nome: "Zagueiro 8",
    slug: "zagueiro-8",
    foto: "/images/jogadores/jogador_padrao_24.jpg",
    posicao: "ZAG",
    rankingPontos: 70,
    vitorias: 5,
    gols: 2,
    assistencias: 2,
    estrelas: { estrelas: 3, atualizadoEm: hoje, adminId: "1" },
    mensalista: false,
  },
  {
    id: "25",
    nome: "Meia 7",
    slug: "meia-7",
    foto: "/images/jogadores/jogador_padrao_25.jpg",
    posicao: "MEI",
    rankingPontos: 72,
    vitorias: 5,
    gols: 2,
    assistencias: 3,
    estrelas: { estrelas: 3, atualizadoEm: hoje, adminId: "1" },
    mensalista: false,
  },
  {
    id: "26",
    nome: "Meia 8",
    slug: "meia-8",
    foto: "/images/jogadores/jogador_padrao_26.jpg",
    posicao: "MEI",
    rankingPontos: 70,
    vitorias: 3,
    gols: 1,
    assistencias: 1,
    estrelas: { estrelas: 2, atualizadoEm: hoje, adminId: "1" },
    mensalista: false,
  },
  {
    id: "27",
    nome: "Atacante 7",
    slug: "atacante-7",
    foto: "/images/jogadores/jogador_padrao_27.jpg",
    posicao: "ATA",
    rankingPontos: 82,
    vitorias: 7,
    gols: 9,
    assistencias: 4,
    estrelas: { estrelas: 4, atualizadoEm: hoje, adminId: "1" },
    mensalista: false,
  },
  {
    id: "28",
    nome: "Atacante 8",
    slug: "atacante-8",
    foto: "/images/jogadores/jogador_padrao_28.jpg",
    posicao: "ATA",
    rankingPontos: 80,
    vitorias: 5,
    gols: 7,
    assistencias: 2,
    estrelas: { estrelas: 3, atualizadoEm: hoje, adminId: "1" },
    mensalista: false,
  },
];
