import { NextResponse } from "next/server";

// Dados mockados para partidas
const mockMatches = [
  // Rodada 1
  {
    id: "match-1",
    round: 1,
    homeTeam: "team-1",
    awayTeam: "team-2",
    homeScore: 2,
    awayScore: 1,
    date: "2025-01-15",
    status: "finished",
  },
  {
    id: "match-2",
    round: 1,
    homeTeam: "team-3",
    awayTeam: "team-4",
    homeScore: 0,
    awayScore: 0,
    date: "2025-01-15",
    status: "finished",
  },
  {
    id: "match-3",
    round: 1,
    homeTeam: "team-1",
    awayTeam: "team-3",
    homeScore: 3,
    awayScore: 2,
    date: "2025-01-16",
    status: "finished",
  },

  // Rodada 2
  {
    id: "match-4",
    round: 2,
    homeTeam: "team-2",
    awayTeam: "team-4",
    homeScore: 1,
    awayScore: 1,
    date: "2025-01-17",
    status: "finished",
  },
  {
    id: "match-5",
    round: 2,
    homeTeam: "team-1",
    awayTeam: "team-4",
    homeScore: 2,
    awayScore: 0,
    date: "2025-01-18",
    status: "finished",
  },
  {
    id: "match-6",
    round: 2,
    homeTeam: "team-2",
    awayTeam: "team-3",
    homeScore: 0,
    awayScore: 2,
    date: "2025-01-19",
    status: "finished",
  },

  // Rodada 3
  {
    id: "match-7",
    round: 3,
    homeTeam: "team-3",
    awayTeam: "team-1",
    homeScore: 1,
    awayScore: 1,
    date: "2025-01-20",
    status: "finished",
  },
  {
    id: "match-8",
    round: 3,
    homeTeam: "team-4",
    awayTeam: "team-2",
    homeScore: 2,
    awayScore: 3,
    date: "2025-01-21",
    status: "finished",
  },
  {
    id: "match-9",
    round: 3,
    homeTeam: "team-4",
    awayTeam: "team-1",
    homeScore: 0,
    awayScore: 1,
    date: "2025-01-22",
    status: "finished",
  },

  // Rodada 4
  {
    id: "match-10",
    round: 4,
    homeTeam: "team-2",
    awayTeam: "team-1",
    homeScore: 2,
    awayScore: 2,
    date: "2025-01-23",
    status: "finished",
  },
  {
    id: "match-11",
    round: 4,
    homeTeam: "team-4",
    awayTeam: "team-3",
    homeScore: 1,
    awayScore: 0,
    date: "2025-01-24",
    status: "finished",
  },
  {
    id: "match-12",
    round: 4,
    homeTeam: "team-3",
    awayTeam: "team-1",
    homeScore: 3,
    awayScore: 1,
    date: "2025-01-25",
    status: "finished",
  },

  // Rodada 5
  {
    id: "match-13",
    round: 5,
    homeTeam: "team-4",
    awayTeam: "team-2",
    homeScore: 0,
    awayScore: 2,
    date: "2025-01-26",
    status: "finished",
  },
  {
    id: "match-14",
    round: 5,
    homeTeam: "team-1",
    awayTeam: "team-4",
    homeScore: 4,
    awayScore: 0,
    date: "2025-01-27",
    status: "finished",
  },
  {
    id: "match-15",
    round: 5,
    homeTeam: "team-3",
    awayTeam: "team-2",
    homeScore: 1,
    awayScore: 1,
    date: "2025-01-28",
    status: "finished",
  },

  // Rodada 6
  {
    id: "match-16",
    round: 6,
    homeTeam: "team-1",
    awayTeam: "team-3",
    homeScore: 2,
    awayScore: 0,
    date: "2025-01-29",
    status: "finished",
  },
  {
    id: "match-17",
    round: 6,
    homeTeam: "team-2",
    awayTeam: "team-4",
    homeScore: 3,
    awayScore: 1,
    date: "2025-01-30",
    status: "finished",
  },
  {
    id: "match-18",
    round: 6,
    homeTeam: "team-1",
    awayTeam: "team-2",
    homeScore: 1,
    awayScore: 0,
    date: "2025-01-31",
    status: "finished",
  },

  // Rodada 7
  {
    id: "match-19",
    round: 7,
    homeTeam: "team-4",
    awayTeam: "team-3",
    homeScore: 2,
    awayScore: 2,
    date: "2025-02-01",
    status: "finished",
  },
  {
    id: "match-20",
    round: 7,
    homeTeam: "team-2",
    awayTeam: "team-1",
    homeScore: 0,
    awayScore: 3,
    date: "2025-02-02",
    status: "finished",
  },
  {
    id: "match-21",
    round: 7,
    homeTeam: "team-3",
    awayTeam: "team-4",
    homeScore: 1,
    awayScore: 1,
    date: "2025-02-03",
    status: "finished",
  },

  // Rodada 8
  {
    id: "match-22",
    round: 8,
    homeTeam: "team-1",
    awayTeam: "team-4",
    homeScore: 3,
    awayScore: 0,
    date: "2025-02-04",
    status: "finished",
  },
  {
    id: "match-23",
    round: 8,
    homeTeam: "team-2",
    awayTeam: "team-3",
    homeScore: 2,
    awayScore: 1,
    date: "2025-02-05",
    status: "finished",
  },
  {
    id: "match-24",
    round: 8,
    homeTeam: "team-4",
    awayTeam: "team-1",
    homeScore: 0,
    awayScore: 2,
    date: "2025-02-06",
    status: "finished",
  },

  // Jogo futuro (próxima rodada)
  {
    id: "match-25",
    round: 9,
    homeTeam: "team-1",
    awayTeam: "team-3",
    homeScore: null,
    awayScore: null,
    date: "2025-02-07",
    status: "scheduled",
  },
];

export async function GET() {
  // Simular delay de rede
  await new Promise((resolve) => setTimeout(resolve, 100));

  return NextResponse.json(mockMatches);
}
