// src/common/enums.ts
export enum Role {
  SUPERADMIN = "SUPERADMIN",
  ADMIN = "ADMIN",
  ATHLETE = "ATHLETE",
  GERENTE = "GERENTE",
  ATLETA = "ATLETA", // alias usado nos testes legados
  SUPORTE = "SUPORTE",
  FINANCEIRO = "FINANCEIRO",
  MARKETING = "MARKETING",
  AUDITORIA = "AUDITORIA",
}

export enum Permission {
  RACHA_CREATE = "RACHA_CREATE",
  RACHA_READ = "RACHA_READ",
  RACHA_UPDATE = "RACHA_UPDATE",
  RACHA_DELETE = "RACHA_DELETE",
  RACHA_MANAGE_ADMINS = "RACHA_MANAGE_ADMINS",
  USER_CREATE = "USER_CREATE",
  USER_READ = "USER_READ",
  USER_UPDATE = "USER_UPDATE",
  USER_DELETE = "USER_DELETE",
  USER_MANAGE_ROLES = "USER_MANAGE_ROLES",
  FINANCE_READ = "FINANCE_READ",
  FINANCE_CREATE = "FINANCE_CREATE",
  FINANCE_UPDATE = "FINANCE_UPDATE",
  FINANCE_DELETE = "FINANCE_DELETE",
  FINANCE_APPROVE = "FINANCE_APPROVE",
  CONFIG_READ = "CONFIG_READ",
  CONFIG_UPDATE = "CONFIG_UPDATE",
  CONFIG_SYSTEM = "CONFIG_SYSTEM",
  ANALYTICS_READ = "ANALYTICS_READ",
  REPORTS_GENERATE = "REPORTS_GENERATE",
  SUPERADMIN_CREATE = "SUPERADMIN_CREATE",
  SUPERADMIN_UPDATE = "SUPERADMIN_UPDATE",
  SUPERADMIN_DELETE = "SUPERADMIN_DELETE",
  AUDIT_READ = "AUDIT_READ",
  AUDIT_CREATE = "AUDIT_CREATE",
  AUDIT_EXPORT = "AUDIT_EXPORT",
  SUPPORT_READ = "SUPPORT_READ",
  SUPPORT_CREATE = "SUPPORT_CREATE",
  SUPPORT_UPDATE = "SUPPORT_UPDATE",
  SUPPORT_DELETE = "SUPPORT_DELETE",
}

export enum SubscriptionStatus {
  ACTIVE = "ACTIVE",
  INACTIVE = "INACTIVE",
  CANCELLED = "CANCELLED",
  PENDING = "PENDING",
}

export enum SubscriptionPlan {
  BASIC = "BASIC",
  PRO = "PRO",
  ENTERPRISE = "ENTERPRISE",
}
